---
- name: Configure logrotate for Plesk PHP-FPM with synthetic creation
  hosts: all
  tasks:

    - name: Find plesk-php* (non-fpm) files in /etc/logrotate.d
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*"
        file_type: file
      register: php_logrotate_all_files

    - name: Filter only plesk-phpXX (not -fmp) base names
      set_fact:
        php_nonfmp_bases: >-
          {{
            php_logrotate_all_files.files
            | map(attribute='path')
            | map('basename')
            | select('match', '^plesk-php[0-9]+$')
            | list
          }}

    - name: Find existing plesk-php*-fmp logrotate files
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*-fmp"
        file_type: file
      register: php_logrotate_fmp_files

    - name: Extract existing fmp base names (simple approach)
      set_fact:
        php_fmp_bases: >-
          {{
            php_logrotate_fmp_files.files
            | map(attribute='path')
            | map('basename')
            | map('replace', '-fmp', '')
            | list
          }}

    - name: Debug - non-fmp bases
      debug:
        var: php_nonfmp_bases

    - name: Debug - fmp bases
      debug:
        var: php_fmp_bases

    - name: Create synthetic -fmp logrotate config for each plesk-phpXX missing it
      shell: |
        echo '/var/log/{{ item }}-fmp/*log {
            daily
            missingok
            notifempty
            sharedscripts
            delaycompress
            dateext
            dateformat -%Y%m%d
            rotate 7
            compress
            create 640 root root
            postrotate
                /bin/kill -SIGUSR1 `cat /run/{{ item }}-fmp.pid 2>/dev/null` 2>/dev/null || true
            endscript
        }' > /etc/logrotate.d/{{ item }}-fmp
      args:
        executable: /bin/bash
      loop: "{{ php_nonfmp_bases }}"
      when: item not in php_fmp_bases

    - name: Re-scan for plesk-php*-fmp logrotate files after synthetic creation
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*-fmp"
        file_type: file
      register: php_logrotate_files_final

    - name: Extract final fmp file paths
      set_fact:
        php_logrotate_paths: "{{ php_logrotate_files_final.files | map(attribute='path') | list }}"

    - name: Debug final logrotate files
      debug:
        msg: "Final logrotate files: {{ php_logrotate_paths }}"

    - name: Create logrotate config for Plesk PHP if files found
      copy:
        dest: /etc/logrotate.plesk-php.conf
        content: |
          # Auto-generated logrotate config for Plesk PHP-FPM
          {% for file in php_logrotate_paths %}
          include {{ file }}
          {% endfor %}
      when: php_logrotate_paths | length > 0

    - name: Remove logrotate config if no plesk-php fmp files found
      file:
        path: /etc/logrotate.plesk-php.conf
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Create systemd service file if files found
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fmp.service
        content: |
          [Unit]
          Description=Rotate logs for Plesk PHP versions only

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/logrotate /etc/logrotate.plesk-php.conf
      when: php_logrotate_paths | length > 0

    - name: Remove systemd service file if no files found
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fmp.service
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Create systemd timer file if files found
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fmp.timer
        content: |
          [Unit]
          Description=Daily timer for Plesk PHP logrotate

          [Timer]
          OnCalendar=daily
          Persistent=true

          [Install]
          WantedBy=timers.target
      when: php_logrotate_paths | length > 0

    - name: Remove systemd timer file if no files found
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fmp.timer
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Wait briefly to ensure systemd sees new unit files
      pause:
        seconds: 2
      when: php_logrotate_paths | length > 0

    - name: Reload systemd to recognize new units if files found
      command: systemctl daemon-reload
      when: php_logrotate_paths | length > 0

    - name: Enable and start logrotate timer if files found
      systemd:
        name: logrotate-plesk-php-fmp.timer
        enabled: yes
        state: started
      when: php_logrotate_paths | length > 0
