---
- name: Ensure synthetic logrotate configs for Plesk PHP-FPM
  hosts: all
  tasks:

    - name: Find plesk-php* (non-fpm) files in /etc/logrotate.d
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*"
        file_type: file
      register: php_logrotate_all_files

    - name: Filter only plesk-phpXX (not -fpm) base names
      set_fact:
        php_nonfpm_bases: >-
          {{
            php_logrotate_all_files.files
            | map(attribute='path')
            | map('basename')
            | select('match', '^plesk-php[0-9]+$')
            | list
          }}

    - name: Find existing plesk-php*-fpm logrotate files
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*-fpm"
        file_type: file
      register: php_logrotate_fpm_files

    - name: Extract existing fpm base names
      set_fact:
        php_fpm_bases: >-
          {{
            php_logrotate_fpm_files.files
            | map(attribute='path')
            | map('basename')
            | map('regex_replace', '^plesk-php([0-9]+)-fpm$', 'plesk-php\\1')
            | list
          }}

    - name: Debug - non-fpm bases
      debug:
        var: php_nonfpm_bases

    - name: Debug - fpm bases
      debug:
        var: php_fpm_bases

    - name: Create synthetic -fpm logrotate config for each plesk-phpXX missing it
      shell: |
        echo '/var/log/{{ item }}-fpm/*log {
            daily
            missingok
            notifempty
            sharedscripts
            delaycompress
            dateext
            dateformat -%Y%m%d
            rotate 7
            compress
            create 640 root root
            postrotate
                /bin/kill -SIGUSR1 `cat /run/{{ item }}-fpm.pid 2>/dev/null` 2>/dev/null || true
            endscript
        }' > /etc/logrotate.d/{{ item }}-fpm
      args:
        executable: /bin/bash
      loop: "{{ php_nonfpm_bases }}"
      when: item not in php_fpm_bases

    - name: Re-scan for plesk-php*-fpm logrotate files after synthetic creation
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*-fpm"
        file_type: file
      register: php_logrotate_files_final

    - name: Extract final fpm file paths
      set_fact:
        php_logrotate_paths: "{{ php_logrotate_files_final.files | map(attribute='path') | list }}"

    - name: Debug final logrotate files
      debug:
        msg: "Final logrotate files: {{ php_logrotate_paths }}"

    - name: Create logrotate config for Plesk PHP if files found
      copy:
        dest: /etc/logrotate.plesk-php.conf
        content: |
          # Auto-generated logrotate config for Plesk PHP-FPM
          {% for file in php_logrotate_paths %}
          include {{ file }}
          {% endfor %}
      when: php_logrotate_paths | length > 0

    - name: Remove logrotate config if no plesk-php fpm files found
      file:
        path: /etc/logrotate.plesk-php.conf
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Create systemd service file if files found
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fpm.service
        content: |
          [Unit]
          Description=Rotate logs for Plesk PHP versions only

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/logrotate /etc/logrotate.plesk-php.conf
      when: php_logrotate_paths | length > 0

    - name: Remove systemd service file if no files found
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fpm.service
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Create systemd timer file if files found
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fpm.timer
        content: |
          [Unit]
          Description=Daily timer for Plesk PHP logrotate

          [Timer]
          OnCalendar=daily
          Persistent=true

          [Install]
          WantedBy=timers.target
      when: php_logrotate_paths | length > 0

    - name: Remove systemd timer file if no files found
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fpm.timer
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Wait briefly to ensure systemd sees new unit files
      pause:
        seconds: 2
      when: php_logrotate_paths | length > 0

    - name: Reload systemd to recognize new units if files found
      command: systemctl daemon-reload
      when: php_logrotate_paths | length > 0

    - name: Enable and start logrotate timer if files found
      systemd:
        name: logrotate-plesk-php-fpm.timer
        enabled: yes
        state: started
      when: php_logrotate_paths | length > 0
