---
- name: Configurar logrotate para Plesk PHP-FPM si es necesario
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    logrotate_dir: /etc/logrotate.d

  tasks:

    - name: Buscar archivos logrotate existentes plesk-php*-fpm
      find:
        paths: "{{ logrotate_dir }}"
        patterns: "plesk-php*-fpm"
        file_type: file
      register: fpm_logrotate_files

    - name: Buscar archivos logrotate existentes plesk-php* excluyendo -fpm
      find:
        paths: "{{ logrotate_dir }}"
        patterns: "plesk-php*"
        file_type: file
      register: php_logrotate_files

    - name: Filtrar archivos plesk-php excluyendo los que contienen -fpm
      set_fact:
        php_non_fpm_files: "{{ php_logrotate_files.files | reject('search', '-fpm') | list }}"

    - name: Extraer nombres base para archivos sin -fpm (sin path)
      set_fact:
        php_non_fpm_bases: "{{ php_non_fpm_files | map(attribute='path') | map('basename') | map('regex_replace', '^plesk-(php[0-9]+)$', '\\1') | list }}"

    - name: Extraer nombres base para archivos -fpm (sin path ni sufijo -fpm)
      set_fact:
        fpm_bases: "{{ fpm_logrotate_files.files | map(attribute='path') | map('basename') | map('regex_replace', '^plesk-(php[0-9]+)-fpm$', '\\1') | list }}"

    - name: Determinar archivos -fpm que faltan (de los que hay sin -fpm)
      set_fact:
        missing_fpm_bases: "{{ php_non_fpm_bases | difference(fpm_bases) }}"

    - name: Crear archivos logrotate plesk-php*-fpm que faltan
      copy:
        dest: "{{ logrotate_dir }}/plesk-{{ item }}-fpm"
        content: |
          /var/log/plesk-{{ item }}-fpm/*log {
              daily
              missingok
              notifempty
              sharedscripts
              delaycompress
              dateext
              dateformat -%Y%m%d
              rotate 7
              compress
              create 640 root root
              postrotate
                  /bin/kill -SIGUSR1 `cat /run/plesk-{{ item }}-fpm.pid 2>/dev/null` 2>/dev/null || true
              endscript
          }
        owner: root
        group: root
        mode: '0640'
      loop: "{{ missing_fpm_bases }}"
      when: missing_fpm_bases | length > 0

    - name: Actualizar lista de archivos fpm tras creación
      find:
        paths: "{{ logrotate_dir }}"
        patterns: "plesk-php*-fpm"
        file_type: file
      register: fpm_logrotate_files_updated

    - name: Extraer lista completa de archivos fpm para incluir
      set_fact:
        fpm_files_paths: "{{ fpm_logrotate_files_updated.files | map(attribute='path') | list }}"

    - name: Crear archivo include para logrotate de Plesk PHP-FPM
      copy:
        dest: /etc/logrotate.d/plesk-php-fpm-include
        content: |
          {{ fpm_files_paths | map('basename') | map('regex_replace', '^(.*)$', '/etc/logrotate.d/\\1') | join('\n') }}
      when: fpm_files_paths | length > 0
      notify: Reload logrotate

    - name: Eliminar archivo include si no hay archivos fpm
      file:
        path: /etc/logrotate.d/plesk-php-fpm-include
        state: absent
      when: fpm_files_paths | length == 0
      notify: Reload logrotate

    - name: Crear systemd service para logrotate fpm
      copy:
        dest: /etc/systemd/system/plesk-php-fpm-logrotate.service
        content: |
          [Unit]
          Description=Logrotate Plesk PHP-FPM logs
          Wants=network.target
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/logrotate /etc/logrotate.d/plesk-php-fpm-include

          [Install]
          WantedBy=multi-user.target
      when: fpm_files_paths | length > 0
      notify: Reload systemd

    - name: Eliminar systemd service si no hay archivos fpm
      file:
        path: /etc/systemd/system/plesk-php-fpm-logrotate.service
        state: absent
      when: fpm_files_paths | length == 0
      notify: Reload systemd

    - name: Crear systemd timer para logrotate fpm
      copy:
        dest: /etc/systemd/system/plesk-php-fpm-logrotate.timer
        content: |
          [Unit]
          Description=Timer for Plesk PHP-FPM logrotate

          [Timer]
          OnCalendar=daily
          Persistent=true

          [Install]
          WantedBy=timers.target
      when: fpm_files_paths | length > 0
      notify: Reload systemd

    - name: Eliminar systemd timer si no hay archivos fpm
      file:
        path: /etc/systemd/system/plesk-php-fpm-logrotate.timer
        state: absent
      when: fpm_files_paths | length == 0
      notify: Reload systemd

    - name: Habilitar y arrancar timer si hay archivos fpm
      systemd:
        name: plesk-php-fpm-logrotate.timer
        enabled: yes
        state: started
      when: fpm_files_paths | length > 0

    - name: Deshabilitar timer si no hay archivos fpm
      systemd:
        name: plesk-php-fpm-logrotate.timer
        enabled: no
        state: stopped
      when: fpm_files_paths | length == 0

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Reload logrotate
      command: /usr/sbin/logrotate --debug /etc/logrotate.conf
      # --debug no rota, solo simula para comprobar configuración
