---
- name: Gestionar logrotate para Plesk PHP-FPM
  hosts: all
  become: yes
  vars:
    logrotate_dir: /etc/logrotate.d
    master_config: /etc/logrotate.plesk-php.conf

  tasks:
    - name: Buscar archivos plesk-php* (no FPM)
      find:
        paths: "{{ logrotate_dir }}"
        patterns: "plesk-php*"
        file_type: file
      register: php_logrotate_files

    - name: Filtrar solo bases PHP (sin -fpm)
      set_fact:
        php_nonfpm_bases: "{{ php_logrotate_files.files | map(attribute='path') | select('search', 'plesk-php[0-9]+$') | map('basename') | list }}"

    - name: Buscar archivos plesk-php*-fpm existentes
      find:
        paths: "{{ logrotate_dir }}"
        patterns: "plesk-php*-fpm"
        file_type: file
      register: php_fpm_files

    - name: Extraer bases de FPM existentes
      set_fact:
        php_fpm_bases: "{{ php_fpm_files.files | map(attribute='path') | map('basename') | map('regex_replace', '-fpm$', '') | list }}"

    - name: Detectar versiones que faltan (gap analysis)
      set_fact:
        missing_fpm_bases: "{{ php_nonfpm_bases | difference(php_fpm_bases) }}"

    - name: Crear archivos logrotate FPM faltantes
      shell: |
        cat > {{ logrotate_dir }}/{{ item }}-fpm <<EOF
/var/log/{{ item }}-fpm/*log {
    daily
    missingok
    notifempty
    sharedscripts
    delaycompress
    dateext
    dateformat -%Y%m%d
    rotate 7
    compress
    create 640 root root
    postrotate
        /bin/kill -SIGUSR1 \`cat /run/{{ item }}-fpm.pid 2>/dev/null\` 2>/dev/null || true
    endscript
}
EOF
      loop: "{{ missing_fpm_bases }}"
      when: missing_fpm_bases | length > 0

    - name: Re-escanear todos los archivos FPM
      find:
        paths: "{{ logrotate_dir }}"
        patterns: "plesk-php*-fpm"
        file_type: file
      register: all_fpm_files

    - name: Crear master config que incluya todos los FPM
      copy:
        dest: "{{ master_config }}"
        content: |
          {% for f in all_fpm_files.files %}
          include {{ f.path }}
          {% endfor %}
      when: all_fpm_files.files | length > 0

    - name: Configurar systemd service y timer (ejemplo)
      block:
        - name: Crear systemd service para logrotate Plesk PHP-FPM
          copy:
            dest: /etc/systemd/system/logrotate-plesk-php.service
            content: |
              [Unit]
              Description=Logrotate for Plesk PHP-FPM

              [Service]
              Type=oneshot
              ExecStart=/usr/sbin/logrotate {{ master_config }}

        - name: Crear systemd timer para logrotate Plesk PHP-FPM
          copy:
            dest: /etc/systemd/system/logrotate-plesk-php.timer
            content: |
              [Unit]
              Description=Daily logrotate for Plesk PHP-FPM

              [Timer]
              OnCalendar=daily
              Persistent=true

              [Install]
              WantedBy=timers.target

        - name: Recargar systemd y habilitar timer
          systemd:
            daemon_reload: yes
            name: logrotate-plesk-php.timer
            enabled: yes
            state: started
      when: all_fpm_files.files | length > 0

    - name: Limpiar master config y systemd si no hay FPM
      block:
        - name: Eliminar master config si no hay FPM
          file:
            path: "{{ master_config }}"
            state: absent

        - name: Eliminar systemd service y timer si no hay FPM
          file:
            path: "/etc/systemd/system/logrotate-plesk-php.{{ item }}"
            state: absent
          loop:
            - service
            - timer

        - name: Recargar systemd
          systemd:
            daemon_reload: yes
      when: all_fpm_files.files | length == 0
