---
- name: Configure logrotate for Plesk PHP-FPM only if relevant files exist
  hosts: all
  become: true
  tasks:

    - name: Find plesk-php*-fpm logrotate files
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*-fpm"
        file_type: file
      register: php_logrotate_files

    - name: Extract file paths
      set_fact:
        php_logrotate_paths: "{{ php_logrotate_files.files | map(attribute='path') | list }}"

    - name: Debug found logrotate files
      debug:
        msg: "{{ php_logrotate_paths }}"

    # Si NO hay archivos fpm, buscar binarios plesk-php** y crear los fpm
    - name: Find plesk-php** binaries if no fpm logrotate files exist
      find:
        paths: /opt/plesk/php/
        patterns: "plesk-php*"
        file_type: file
      register: php_binaries
      when: php_logrotate_paths | length == 0

    - name: Extract PHP versions from binaries
      set_fact:
        detected_php_versions: "{{ php_binaries.files | map(attribute='path') | map('basename') | list }}"
      when: php_logrotate_paths | length == 0

    - name: Create synthetic plesk-php*-fpm logrotate configs for each PHP version
      shell: |
        echo '/var/log/{{ item }}-fpm/*log {
            daily
            missingok
            notifempty
            sharedscripts
            delaycompress
            dateext
            dateformat -%Y%m%d
            rotate 7
            compress
            create 640 root root
            postrotate
                /bin/kill -SIGUSR1 `cat /run/{{ item }}-fpm.pid 2>/dev/null` 2>/dev/null || true
            endscript
        }' | tee /etc/logrotate.d/{{ item }}-fpm
      args:
        executable: /bin/bash
      loop: "{{ detected_php_versions | default([]) }}"
      when: php_logrotate_paths | length == 0 and detected_php_versions is defined

    # Vuelve a buscar los fpm después de crear sintéticos
    - name: Re-scan for plesk-php*-fpm logrotate files after synthetic creation
      find:
        paths: /etc/logrotate.d/
        patterns: "plesk-php*-fpm"
        file_type: file
      register: php_logrotate_files_after
      when: php_logrotate_paths | length == 0

    - name: Update php_logrotate_paths if synthetic created
      set_fact:
        php_logrotate_paths: "{{ php_logrotate_files_after.files | map(attribute='path') | list }}"
      when: php_logrotate_paths | length == 0

    - name: Debug final logrotate files
      debug:
        msg: "{{ php_logrotate_paths }}"

    - name: Create logrotate config for Plesk PHP if files found
      copy:
        dest: /etc/logrotate.plesk-php.conf
        content: |
          # Auto-generated logrotate config for Plesk PHP-FPM
          {% for file in php_logrotate_paths %}
          include {{ file }}
          {% endfor %}
      when: php_logrotate_paths | length > 0

    - name: Remove logrotate config if no plesk-php fpm files found
      file:
        path: /etc/logrotate.plesk-php.conf
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Create systemd service file if files found
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fpm.service
        content: |
          [Unit]
          Description=Rotate logs for Plesk PHP versions only

          [Service]
          Type=oneshot
          ExecStart=/usr/sbin/logrotate /etc/logrotate.plesk-php.conf
      when: php_logrotate_paths | length > 0

    - name: Remove systemd service file if no files found
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fpm.service
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Create systemd timer file if files found
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fpm.timer
        content: |
          [Unit]
          Description=Daily timer for Plesk PHP logrotate

          [Timer]
          OnCalendar=daily
          Persistent=true

          [Install]
          WantedBy=timers.target
      when: php_logrotate_paths | length > 0

    - name: Remove systemd timer file if no files found
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fpm.timer
        state: absent
      when: php_logrotate_paths | length == 0

    - name: Wait briefly to ensure systemd sees new unit files
      pause:
        seconds: 2
      when: php_logrotate_paths | length > 0

    - name: Reload systemd to recognize new units if files found
      command: systemctl daemon-reload
      when: php_logrotate_paths | length > 0

    - name: Enable and start logrotate timer if files found
      systemd:
        name: logrotate-plesk-php-fpm.timer
        enabled: yes
        state: started
      when: php_logrotate_paths | length > 0
