- name: Configure logrotate for Plesk PHP-FPM if needed
  hosts: all
  become: yes
  vars:
    logrotate_dir: /etc/logrotate.d
  tasks:

    - name: Find plesk-php*-fpm logrotate files
      find:
        paths: "{{ logrotate_dir }}"
        patterns: 'plesk-php*-fpm*'
      register: fpm_files

    - name: Find plesk-php* logrotate files excluding -fpm
      find:
        paths: "{{ logrotate_dir }}"
        patterns: 'plesk-php*'
      register: php_files

    - name: Filter plesk-php files excluding those with -fpm in name
      set_fact:
        non_fpm_php_files: >-
          {{ php_files.files | map(attribute='path') | reject('search', '-fpm') | list }}

    - name: Determine which fpm files need to be created
      set_fact:
        needed_fpm_files: >-
          {{ non_fpm_php_files
            | map('regex_replace', '^.*/plesk-(php[0-9]+)$', '\\1')
            | select('noneof', fpm_files.files | map(attribute='path') | map('regex_search', 'plesk-(php[0-9]+)-fpm') | map('first') | list)
            | map('regex_replace', '^(php[0-9]+)$', '/etc/logrotate.d/plesk-\\1-fpm') | list }}

    - name: Debug needed fpm files to create
      debug:
        var: needed_fpm_files

    - name: Create missing plesk-php*-fpm logrotate files
      copy:
        dest: "{{ item }}"
        content: |
          /var/log/{{ item | regex_replace('^.*/', '') }}/*log {
              daily
              missingok
              notifempty
              sharedscripts
              delaycompress
              dateext
              dateformat -%Y%m%d
              rotate 7
              compress
              create 640 root root
              postrotate
                  /bin/kill -SIGUSR1 `cat /run/{{ item | regex_replace('^.*/', '') }}.pid 2>/dev/null` 2>/dev/null || true
              endscript
          }
      loop: "{{ needed_fpm_files }}"
      notify: Reload systemd

    - name: Re-collect fpm files after creating missing ones
      find:
        paths: "{{ logrotate_dir }}"
        patterns: 'plesk-php*-fpm*'
      register: fpm_files_updated

    - name: Set fact with all plesk-php*-fpm files
      set_fact:
        logrotate_php_fpm_files: "{{ fpm_files_updated.files | map(attribute='path') | list }}"

    - name: Debug final list of plesk-php*-fpm logrotate files
      debug:
        var: logrotate_php_fpm_files

    - name: Create combined logrotate include config if fpm files found
      copy:
        dest: /etc/logrotate.plesk-php.conf
        content: |
          {% for file in logrotate_php_fpm_files %}
          include {{ file }}
          {% endfor %}
      when: logrotate_php_fpm_files | length > 0
      notify: Reload systemd

    - name: Remove combined logrotate include config if no fpm files
      file:
        path: /etc/logrotate.plesk-php.conf
        state: absent
      when: logrotate_php_fpm_files | length == 0
      notify: Reload systemd

    - name: Create systemd service file if fpm files exist
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fpm.service
        content: |
          [Unit]
          Description=Logrotate for Plesk PHP-FPM

          [Service]
          ExecStart=/usr/sbin/logrotate /etc/logrotate.plesk-php.conf
      when: logrotate_php_fpm_files | length > 0
      notify: Reload systemd

    - name: Remove systemd service file if no fpm files
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fpm.service
        state: absent
      when: logrotate_php_fpm_files | length == 0
      notify: Reload systemd

    - name: Create systemd timer file if fpm files exist
      copy:
        dest: /etc/systemd/system/logrotate-plesk-php-fpm.timer
        content: |
          [Unit]
          Description=Daily log rotation for Plesk PHP-FPM

          [Timer]
          OnCalendar=daily
          Persistent=true

          [Install]
          WantedBy=timers.target
      when: logrotate_php_fpm_files | length > 0
      notify: Reload systemd

    - name: Remove systemd timer file if no fpm files
      file:
        path: /etc/systemd/system/logrotate-plesk-php-fpm.timer
        state: absent
      when: logrotate_php_fpm_files | length == 0
      notify: Reload systemd

    - name: Enable and start logrotate timer if fpm files exist
      systemd:
        name: logrotate-plesk-php-fpm.timer
        enabled: yes
        state: started
      when: logrotate_php_fpm_files | length > 0

    - name: Disable and stop logrotate timer if no fpm files
      systemd:
        name: logrotate-plesk-php-fpm.timer
        enabled: no
        state: stopped
      when: logrotate_php_fpm_files | length == 0

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
