---
- name: Update and Upgrade Ubuntu Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      command: apt-get update -y

    - name: Upgrade all installed packages
      command: apt-get upgrade -y

    - name: Autoremove unnecessary packages
      command: apt-get autoremove -y

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot the server if required
      reboot:
      when: reboot_required.stat.exists
